version: '3.7'
services:
    php8-sf6:
        container_name: php8-sf6
        build: php8-sf6
        ports:
            - "9000:8000"
        volumes:
            - ./project:/var/www/html

    database:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: Ha4kunaM4t4ta
        volumes:
            - db-data:/var/lib/mariadb/data:rw
        ports:
            - "3306"


volumes:
  db-data: